### ISSUE TITLE
通信エラーの表示

### ISSUE THREAD

**Issue by rokka032486** [teritamahamburg/frontend#6]
通信エラーの時に下にポップアップを表示してくれ

**Comment by syuchan1005** [comment]
@rokka032486 
![B6175A4A-D172-4C3B-BDAE-F70799F38436](https://user-images.githubusercontent.com/8733829/59241535-08368900-8c43-11e9-9b7f-c7fa4f04e961.jpeg)

こんな感じの出せばいいですか

**Comment by rokka032486** [comment]
@syuchan1005 
いいんじゃないですかね
